# Generated by Django 2.0 on 2017-12-26 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20171225_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 18, 28, 35, 814754, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
