# Generated by Django 2.0 on 2017-12-26 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20171226_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 18, 57, 34, 965624, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
