# Generated by Django 2.0 on 2017-12-26 19:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20171226_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 19, 10, 39, 691058, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
