# Generated by Django 2.0.1 on 2018-01-05 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20180105_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ShopUserProfile',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 7, 15, 42, 48, 378717, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
