# Generated by Django 2.0.1 on 2018-01-06 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20180105_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 17, 50, 24, 832484, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
