# Generated by Django 2.0.1 on 2018-01-06 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20180106_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 18, 35, 40, 229295, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
