# Generated by Django 2.0.1 on 2018-01-10 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20180110_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 14, 1, 40, 693578, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
