# Generated by Django 2.0 on 2018-01-17 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20180110_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 13, 8, 58, 861500, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
